version: "3"

services:

  mailer-svc:
    build:
      context: "."
    networks:
      - "mailer-svc"
    ports:
      - "50053:50051"
    environment:
      NODE_ENV: "test"
      HOST: "0.0.0.0"
      PORT: "50051"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: "on-failure"

networks:
  mailer-svc:
